import { useState, useEffect, useCallback } from 'react';
import * as duckdb from '@duckdb/duckdb-wasm';
import duckdb_wasm from '@duckdb/duckdb-wasm/dist/duckdb-mvp.wasm?url';
import mvp_worker from '@duckdb/duckdb-wasm/dist/duckdb-browser-mvp.worker.js?url';
import duckdb_wasm_eh from '@duckdb/duckdb-wasm/dist/duckdb-eh.wasm?url';
import eh_worker from '@duckdb/duckdb-wasm/dist/duckdb-browser-eh.worker.js?url';

// Define the shape of our summary statistics
export interface HotelSummaryStats {
  property_name: string;
  stay_date: Date;
  rooms_cy: number;
  revenue_cy: number;
  rooms_ly_actual: number;
  rev_ly_actual: number;
  rev_budget: number;
  rooms_budget: number;
  available_rooms: number;
  occ_cy: number;
  occ_py: number;
  occ_budget: number;
  adr_cy: number;
  adr_py: number;
  adr_budget: number;
  revpar_cy: number;
  revpar_py: number;
  revpar_budget: number;
  occ_var: number;
  adr_var: number;
  revpar_var: number;
  rev_to_budget: number;
  budget_reach_pct: number;
}

// Singleton for DuckDB WASM instance
let dbPromise: Promise<duckdb.AsyncDuckDB> | null = null;

async function getDuckDB() {
  if (dbPromise) return dbPromise;

  dbPromise = (async () => {
    // Select a bundle based on browser checks
    const MANUAL_BUNDLES: duckdb.DuckDBBundles = {
      mvp: {
        mainModule: duckdb_wasm,
        mainWorker: mvp_worker,
      },
      eh: {
        mainModule: duckdb_wasm_eh,
        mainWorker: eh_worker,
      },
    };

    const bundle = await duckdb.selectBundle(MANUAL_BUNDLES);
    const worker = new Worker(bundle.mainWorker!);
    const logger = new duckdb.ConsoleLogger();
    const db = new duckdb.AsyncDuckDB(logger, worker);
    
    await db.instantiate(bundle.mainModule, bundle.pthreadWorker);
    return db;
  })();

  return dbPromise;
}

export function useHotelAnalytics() {
  const [isReady, setIsReady] = useState(false);
  const [error, setError] = useState<Error | null>(null);

  useEffect(() => {
    getDuckDB()
      .then(() => setIsReady(true))
      .catch((err) => setError(err));
  }, []);

  /**
   * Retrieves summary statistics for a given hotel and date range from the 'Current' snapshot.
   */
  const getSummaryStats = useCallback(
    async (hotelName: string, year: number, month: number): Promise<HotelSummaryStats | null> => {
      if (!isReady) throw new Error("DuckDB is not ready yet.");

      try {
        const db = await getDuckDB();
        const conn = await db.connect();
        
        // Use DuckDB's HTTPFS to read directly from the public folder
        // The file was generated by our bigquery sync script
        const parquetUrl = '/data/dashboard_current.parquet';
        
        // Build the query. We sum/average everything for the given month.
        // DuckDB read_parquet can read remote files via url.
        const query = `
          SELECT 
            property_name,
            SUM(rooms_cy) as rooms_cy,
            SUM(revenue_cy) as revenue_cy,
            SUM(rooms_ly_actual) as rooms_ly_actual,
            SUM(rev_ly_actual) as rev_ly_actual,
            SUM(rev_budget) as rev_budget,
            SUM(rooms_budget) as rooms_budget,
            SUM(available_rooms) as available_rooms,
            -- Recalculate ratios over the entire month to ensure correct weighted averages
            SUM(rooms_cy) / NULLIF(SUM(available_rooms), 0) as occ_cy,
            SUM(rooms_ly_actual) / NULLIF(SUM(available_rooms), 0) as occ_py,
            SUM(rooms_budget) / NULLIF(SUM(available_rooms), 0) as occ_budget,
            SUM(revenue_cy) / NULLIF(SUM(rooms_cy), 0) as adr_cy,
            SUM(rev_ly_actual) / NULLIF(SUM(rooms_ly_actual), 0) as adr_py,
            SUM(rev_budget) / NULLIF(SUM(rooms_budget), 0) as adr_budget,
            SUM(revenue_cy) / NULLIF(SUM(available_rooms), 0) as revpar_cy,
            SUM(rev_ly_actual) / NULLIF(SUM(available_rooms), 0) as revpar_py,
            SUM(rev_budget) / NULLIF(SUM(available_rooms), 0) as revpar_budget,
            
            -- Variances
            (SUM(rooms_cy) / NULLIF(SUM(available_rooms), 0)) - (SUM(rooms_ly_actual) / NULLIF(SUM(available_rooms), 0)) as occ_var,
            (SUM(revenue_cy) / NULLIF(SUM(rooms_cy), 0)) - (SUM(rev_ly_actual) / NULLIF(SUM(rooms_ly_actual), 0)) as adr_var,
            (SUM(revenue_cy) / NULLIF(SUM(available_rooms), 0)) - (SUM(rev_ly_actual) / NULLIF(SUM(available_rooms), 0)) as revpar_var,
            SUM(rev_budget) - SUM(revenue_cy) as rev_to_budget,
            SUM(revenue_cy) / NULLIF(SUM(rev_budget), 0) as budget_reach_pct
          FROM read_parquet('${parquetUrl}')
          WHERE property_name = '${hotelName.replace(/'/g, "''")}'
            AND date_part('year', stay_date) = ${year}
            AND date_part('month', stay_date) = ${month}
          GROUP BY property_name;
        `;

        const result = await conn.query(query);
        await conn.close();

        if (result.numRows === 0) return null;

        // Convert the Apache Arrow row to a standard Javascript Object
        const row = result.get(0);
        return row ? (row.toJSON() as HotelSummaryStats) : null;
      } catch (err: any) {
        console.error("Error querying summary stats:", err);
        throw err;
      }
    },
    [isReady]
  );
  
  /**
   * You can add getTrendStats() here to read from '/data/dashboard_trend.parquet' 
   * grouping by snapshot_date to chart how OTB climbed.
   */

  return { isReady, error, getSummaryStats };
}
